/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HRApp;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void departmentEmployeeArraySizeLimit() {
        Department department = new Department();

        for (int i = 0; i < 10; i++) {
            department.addEmployee(new Employee());
        }

        assertThrows(IndexOutOfBoundsException.class, () -> department.addEmployee(new Employee()));
    }
}
