/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HRApp;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void departmentEmployeeArraySizeLimit() {
        Department department = new Department();

        for (int i = 0; i < 10; i++) {
            department.addEmployee(new Employee());
        }

        assertThrows(IndexOutOfBoundsException.class, () -> department.addEmployee(new Employee()));
    }

    @Test
    void nonNullEmployeesInDeparment() {
        Department department = new Department();

        for (int i = 0; i < 5; i++) {
            department.addEmployee(new Employee());
        }

        Employee[] employees = department.getEmployees();

        for (Employee e : employees) {
            assertNotNull(e);
        }

        assertEquals(5, employees.length);
    }

    @Test
    void numberOfEmployeesInDepartment() {
        Department department = new Department();

        for (int i = 0; i < 5; i++) {
            department.addEmployee(new Employee());
        }

        assertEquals(5, department.getNumberOfEmployees());
    }

    @Test
    void getEmployeeById() {
        Department department = new Department();

        for (int i = 0; i < 5; i++) {
            department.addEmployee(new Employee(i, "Name-" + i, 1000 * i));
        }

        Employee employeeExists = department.getEmployeeById(2);

        assertNotNull(employeeExists);

        Employee employeeNoExists = department.getEmployeeById(5);

        assertNull(employeeNoExists);
    }
}
