/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HRApp;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void departmentEmployeeArraySizeLimit() {
        Department department = new Department();

        for (int i = 0; i < 10; i++) {
            department.addEmployee(new Employee());
        }

        assertThrows(IndexOutOfBoundsException.class, () -> department.addEmployee(new Employee()));
    }

    @Test
    void nonNullEmployeesInDeparment() {
        Department department = new Department();

        for (int i = 0; i < 5; i++) {
            department.addEmployee(new Employee());
        }

        Employee[] employees = department.getEmployees();

        for (Employee e : employees) {
            assertNotNull(e);
        }

        assertEquals(5, employees.length);
    }
}
