/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HRApp;

public class App {

    public static void main(String[] args) {
        Department department = new Department();

        for (int i = 0; i < 5; i++) {
            department.addEmployee(new Employee(i, "Name-" + i, 1000 * i));
        }

        for (int i = 0; i < 10; i++) {
            System.out.println(department.getEmployees()[i].getName());
        }
    }
}
